= Genetical algorithms
:experimental:
:nofooter:
:source-highlighter: highlightjs
:sectnums:
:stem: latexmath
:toc:
:xrefstyle: short


[[general_description]]
== General description 
This project consists on an evaluative comparison of the performance of genetic algorithms, exhaustive recursion and dynamic programming when it comes to solving problems with NP complexity. The four problems involved are: subset sum, partition, bin packing, and double knapsack.

[[user_manual]]
== User manual

[[build]]
=== Build
Pre-requisites:

Firstly, device must have python3 installed, with pip.

Install optuna, plotly, and sklearn with the following commands

`pip install optuna`

`pip install plotly`

`pip install scikit-learn`

[[usage]]
=== Usage
Use the `make run` command to run the simulation.

NOTE: The `optuna_studies/` folder contains summaries of genetic algorithm optimizations, while graphs related to the process will be generated in folders at the source directory.

[[credits]]
== Credits

Completed by _stack_underflow_, 2025.

- Andrey Bejarano <gerardo.bejaranodiaz@ucr.ac.cr>

- Evan Chen <evan.chen@ucr.ac.cr>

- Albin Monge <albin.monge@ucr.ac.cr>